// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLrGyEH0dthbogwl0iQ3nEKHYn5QayZ4c',
    appId: '1:704505853279:web:0daa294f2bad576943f2ea',
    messagingSenderId: '704505853279',
    projectId: 'minna-65c33',
    authDomain: 'minna-65c33.firebaseapp.com',
    databaseURL: 'https://minna-65c33.firebaseio.com',
    storageBucket: 'minna-65c33.appspot.com',
    measurementId: 'G-MTELZ128E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV6rDsMwKpPCcni4MGIe16QyQd4HD0J3o',
    appId: '1:704505853279:android:627d83077648d32043f2ea',
    messagingSenderId: '704505853279',
    projectId: 'minna-65c33',
    databaseURL: 'https://minna-65c33.firebaseio.com',
    storageBucket: 'minna-65c33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATHm6fg2p1morP-dRDWDaXGqnA6mUWafQ',
    appId: '1:704505853279:ios:4d8eba1c20c06d4443f2ea',
    messagingSenderId: '704505853279',
    projectId: 'minna-65c33',
    databaseURL: 'https://minna-65c33.firebaseio.com',
    storageBucket: 'minna-65c33.appspot.com',
    androidClientId: '704505853279-ku5khu4qg7p5goide3i5lq0k27a67qnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.secureMinnaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATHm6fg2p1morP-dRDWDaXGqnA6mUWafQ',
    appId: '1:704505853279:ios:4d8eba1c20c06d4443f2ea',
    messagingSenderId: '704505853279',
    projectId: 'minna-65c33',
    databaseURL: 'https://minna-65c33.firebaseio.com',
    storageBucket: 'minna-65c33.appspot.com',
    androidClientId: '704505853279-ku5khu4qg7p5goide3i5lq0k27a67qnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.secureMinnaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLrGyEH0dthbogwl0iQ3nEKHYn5QayZ4c',
    appId: '1:704505853279:web:58dcdca38335cd0f43f2ea',
    messagingSenderId: '704505853279',
    projectId: 'minna-65c33',
    authDomain: 'minna-65c33.firebaseapp.com',
    databaseURL: 'https://minna-65c33.firebaseio.com',
    storageBucket: 'minna-65c33.appspot.com',
    measurementId: 'G-0N9D2LR658',
  );

}